#:import os os

### Экран незарегистрированного пользователя
<InputZone@MDTextField>:
    multiline: False
    halign: 'center'
    line_color_normal: "white"
    hint_text_color_normal: "white"
    font_size: '24sp'

### Экран авторизации
<Autorization>:
    user_name: login
    user_surname: password

    MDFloatLayout:
        MDSpinner:
            id: spinner
            size_hint: None, None
            size: dp(46), dp(46)
            pos_hint: {'center_x': .5, 'center_y': .5}
            active: False

        MDGridLayout: 
            cols: 1
            padding: 50
            size_hint_x: 1
            
            MDLabel:

            MDLabel:

            InputZone:
                id: login
                hint_text: 'Imie'
                max_text_length: 15 

            InputZone:
                id: password
                hint_text: 'Nazwisko'
                max_text_length: 15 
            
            MDGridLayout: 
                cols: 3
                size_hint_x: 1

                MDCheckbox:
                    id: remember_me
                    halign: 'center'
                    size_hint_x: .33
                    active: True
                    on_active:
                        root.checkbox_remember_me(remember_me.active)

                MDLabel:
                    text: 'Zapamiętaj mnie'
                    font_size: '16sp'
                    halign: 'center'
                    size_hint_x: .33

                MDLabel:
                    size_hint_x: .33

            MDLabel:

            MDRectangleFlatIconButton:
                icon: 'account-hard-hat-outline'
                text: "Logowanie"
                font_size: '28sp'
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                size_hint_x: 1
                on_release:
                    spinner.active = True
                    root.manager.transition.direction = 'left'
                    root.manager.transition.duration = 0.2
                    root.btn_logowanie()
                
            MDLabel:

            MDLabel:
                text: 'Instalacje elektryczne\nROKBIT sp. Zo.o.'
                halign: 'center'
                font_size: '12sp'

### После авторизации
<Text@MDLabel>:
    font_size: '18sp'
    halign: 'left'

### Виджет таблицы
<TabelItem>:
    LeftLabel:
        id: left_label

    RightButton:
        id: right_button
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

### Главный экран
<Main>:   
    MDBackdrop:
        id: backdrop
        left_action_items: [["menu", lambda x: backdrop.open()]]
        right_action_items: [["close-box-outline", lambda x: root.btn_wyloguj()]]
        title: root.user
        header_text: 'Dzisiaj: ' + root.today
        back_layer_color: 'black'
        close_icon: 'arrow-up'

        MDBackdropBackLayer:
            id: back

            MDFloatLayout:
                size_hint_x: 1

                MDGridLayout: 
                    cols: 1
                    spacing: 30
                    padding: 50
                    adaptive_size: True
                    size_hint_x: 1
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDRectangleFlatIconButton:
                        icon: 'timer-plus-outline'
                        text: "Dodać"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_dodac()

                    MDRectangleFlatIconButton:
                        icon: 'message-processing'
                        text: "Wyślij"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_wyslij()

                    MDRectangleFlatIconButton:
                        icon: 'table-arrow-up'
                        text: "Tabela"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_memu_tabela()

                    MDRectangleFlatIconButton:
                        icon: 'frequently-asked-questions'
                        text: "Pytać"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_pytac()

                    MDRectangleFlatIconButton:
                        icon: 'format-list-checks'
                        text: "Zadania"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_zadania()

        MDBackdropFrontLayer:
            id: front

            MDFloatLayout:

                MDSpinner:
                    id: spinner
                    size_hint: None, None
                    size: dp(46), dp(46)
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    active: True
 
                MDBoxLayout: 
                    orientation: 'vertical'
                    padding: 30
                    pos_hint: {'center_x': .5, 'center_y': .5}

                    MDGridLayout: 
                        cols: 3
                        size_hint_x: 1
                        size_hint_y: 0.15
                        spacing: 10

                        MDRectangleFlatIconButton:
                            id: godziny
                            icon: 'hours-24'
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            text: 'Godziny'
                            size_hint_x: 1
                            font_size: '16sp'
                            on_release:
                                root.btn_godziny()
                        
                        MDRectangleFlatIconButton:
                            id: obiekt
                            icon: 'home-lightning-bolt'
                            pos_hint: {'center_x': .5, 'center_y': .5}
                            text: 'Obiekt'
                            size_hint_x: 1
                            font_size: '16sp'
                            on_release: 
                                root.btn_obiekt()

                        MDRectangleFlatIconButton:
                            id: date
                            icon: 'calendar-range'
                            text: root.today[:-5]
                            font_size: '16sp'
                            pos_hint: {"center_x": 0.5, "center_y": 0.5}
                            size_hint_x: 1
                            on_release: 
                                root.btn_show_calendar()

                    MDScrollView:
                        size_hint_x: 0.85
                        size_hint_y: 0.7
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        
                        MDList: 
                            id: scroll
                    
                    MDGridLayout: 
                        cols: 2
                        size_hint_x: 1
                        size_hint_y: 0.15

                        Text:
                            id: summa
                            halign: 'center'
                            font_size: '24sp'
                            font_style: 'H6'
                            
                    MDRectangleFlatIconButton:
                        text: "Dodać"
                        font_size: '28sp'
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        size_hint_x: 1
                        on_release:
                            root.btn_dodac()

### Экран календаря
<Calendar>:
    BoxLayout:
        padding: 30
        orientation: "vertical"

        MDRectangleFlatIconButton:
            text: "< Powrót"
            font_size: '28sp'
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size_hint_x: 1
            on_release:
                root.logic.back_from_calendar_to_main_screen()
                root.manager.transition.direction = 'right'
                root.manager.current = "main_screen"

        MDLabel:
            size_hint_y: 0.1

        DatePicker:
            size_hint_y: 0.7
            on_select:
                root.screen_constructor.main_screen.logic.on_save_calendar(self.date)
                root.manager.transition.direction = 'right'
                root.manager.current = "main_screen"

        MDLabel:
            size_hint_y: 0.2

### День в календаре        
<DateButton>:
    id: date_btn
    elevation: .1
    radius: dp(10)
    ripple_behavior: True
    Label:
        text: date_btn.text
        color: date_btn.text_color

### Всплывающее окно добавления godzin
<AddHoursWidget>
    progress_hours_line: hours_line_data.value

    orientation: "vertical"
    size_hint:(None, None)
    height: int(self.widget_height)
    width: int(self.widget_width)
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint_x: 1
    padding: 30

    MDLabel:
        id: current_hours_value
        halign: 'center'
        pos_hint: {'center_x': .5, 'center_y': .5}
        font_size: '52sp'
        text: '0'

    MDLabel:
    
    MDLabel:
        halign: 'center'
        font_size: '24sp'
        font_style: 'H6'
        text: 'Ustaw godzinę'

    MDLabel:

    MDSlider:
        id: hours_line_data
        min: 0
        max: 24
        on_active:
            root.hour_reaction.set_current_value(hours_line_data.value)
            print(hours_line_data.value)
    
    MDLabel:

    MDGridLayout:
        cols: 5    
        width: root.widget_width
        size_hint_x: 1
        pos_hint: {'center_x': .5, 'center_y': .5}

        MDTextButton:
            text: '0'
            size_hint_x: 1
            on_release:
                root.hour_reaction.add_0_godzin()

        MDTextButton:
            text: "8"
            halign: "center"
            font_size: '28sp'
            size_hint_x: 1
            on_release:
                root.hour_reaction.add_8_godzin()

        MDTextButton:
            text: "10"
            halign: "center"
            font_size: '28sp'
            size_hint_x: 1
            on_release:
                root.hour_reaction.add_10_godzin()

        MDTextButton:
            text: "12"
            halign: "center"
            font_size: '28sp'
            size_hint_x: 1
            on_release:
                root.hour_reaction.add_12_godzin()

        MDTextButton:
            text: '24'
            size_hint_x: 1
            on_release:
                root.hour_reaction.add_24_godziny()
    
    MDLabel:

    MDRectangleFlatIconButton:
        pos_hint: {'center_x': .5, 'center_y': .5}
        text: "Ok"
        font_size: '28sp'
        size_hint_x: 1
        on_release:
            root.hour_reaction.press_ok(hours_line_data.value)
    
    MDLabel:

### Всплывающее окно выбора объекта на котором работаешь
<WorkObjects>:
    orientation: "vertical"
    size_hint:(None, None)
    height: int(self.widget_height)
    width: int(self.widget_width)
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint_x: 1
    padding: 30

    MDTextFieldRect:
        id: current_object_value

        size_hint_y: 0.8
        hint_text: 'Renoma'
        mode: "fill"
        max_text_length: 10 
        halign: 'center'
        pos_hint: {'center_x': .5, 'center_y': .5}
        font_size: '52sp'

    MDLabel:
        halign: 'center'
        font_size: '24sp'
        font_style: 'H6'
        text: 'Zaznaczanie obiektu'


    MDScrollView:
        size_hint_y: 1.5
        MDList:
            OneLineAvatarIconListItem:
                MDRectangleFlatButton:
                    text: "Renoma"
                    halign: "center" 
                    font_size: '28sp'
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    size_hint_x: 0.9
                    on_release:
                        root.objects.reaction_on_renoma()

            OneLineAvatarIconListItem:    
                MDRectangleFlatButton:
                    text: "Żarów"
                    halign: "center" 
                    font_size: '28sp'
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    size_hint_x: 0.9
                    on_release:
                        root.objects.reaction_on_zarow()

            OneLineAvatarIconListItem:
                MDRectangleFlatButton:
                    text: "Rędzin"
                    halign: "center" 
                    font_size: '28sp'
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    size_hint_x: 0.9
                    on_release:
                        root.objects.reaction_on_redzin()

    MDLabel:
        size_hint_y: 0.2

    MDRectangleFlatIconButton:
        pos_hint: {'center_x': .5, 'center_y': .5}
        text: "Ok"
        font_size: '28sp'
        size_hint_x: 1
        on_release:
            root.objects.press_ok()
            root.main_screen_logic.dialog_screen_to_set_object.dismiss()
