#:import os os

### Экран незарегистрированного пользователя
<InputZone@MDTextField>:
    multiline: False
    halign: 'center'
    line_color_normal: "white"
    hint_text_color_normal: "white"
    font_size: '24sp'

<Autorization>:
    user_name: login
    user_surname: password

    MDGridLayout: 
        cols: 1
        padding: 50
        size_hint_x: 1
        
        MDLabel:

        MDLabel:

        InputZone:
            id: login
            hint_text: 'Imie'
            max_text_length: 15 

        InputZone:
            id: password
            hint_text: 'Nazwisko'
            max_text_length: 15 
        
        MDGridLayout: 
            cols: 3
            size_hint_x: 1

            MDCheckbox:
                id: 'remember_me'
                halign: 'center'
                size_hint_x: .33
                on_active:
                    root.logic.on_checkbox_active(*args)

            MDLabel:
                text: 'Zapamiętaj mnie'
                font_size: '16sp'
                halign: 'center'
                size_hint_x: .33

            MDLabel:
                size_hint_x: .33

        MDLabel:

        MDRectangleFlatIconButton:
            icon: 'account-hard-hat-outline'
            text: "Logowanie"
            font_size: '28sp'
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size_hint_x: 1
            on_release: 
                root.logic.set_user()
                root.manager.transition.direction = 'left' if root.user_authorized else 'right'
                root.manager.transition.duration = 0.2
                root.manager.current = "main_screen" if root.user_authorized else "authorization_screen"
            
        MDLabel:

        MDLabel:
            text: 'Instalacje elektryczne\nROKBIT sp. Zo.o.'
            halign: 'center'
            font_size: '12sp'

### После авторизации
<Text@MDLabel>:
    font_size: '18sp'
    halign: 'left'

### Виджет таблицы
<MyItemList>:
    LeftLabel:
        id: left_label

    RightButton:
        id: right_button

### Главный экран
<Main>:   
    MDBackdrop:
        id: backdrop
        left_action_items: [["menu", lambda x: backdrop.open()]]
        right_action_items: [["close-box-outline", lambda x: root.btn_wyloguj()]]
        title: root.user
        header_text: 'Dzisiaj: ' + root.today
        back_layer_color: 'black'
        close_icon: 'arrow-up'

        MDBackdropBackLayer:
            id: back

            MDFloatLayout:
                size_hint_x: 1

                MDGridLayout: 
                    cols: 1
                    spacing: 30
                    padding: 50
                    adaptive_size: True
                    size_hint_x: 1
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDRectangleFlatIconButton:
                        icon: 'timer-plus-outline'
                        text: "Dodać"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_dodac()

                    MDRectangleFlatIconButton:
                        icon: 'message-processing'
                        text: "Wyślij"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_wyslij()

                    MDRectangleFlatIconButton:
                        icon: 'table-arrow-up'
                        text: "Tabela"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_memu_tabela()

                    MDRectangleFlatIconButton:
                        icon: 'frequently-asked-questions'
                        text: "Pytać"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_pytac()

                    MDRectangleFlatIconButton:
                        icon: 'format-list-checks'
                        text: "Zadania"
                        font_size: '28sp'
                        size_hint_x: 1
                        on_release:
                            root.btn_menu_zadania()

        MDBackdropFrontLayer:
            id: front
 
            MDBoxLayout: 
                orientation: 'vertical'
                padding: 30

                MDBoxLayout: 
                    orientation: 'horizontal'
                    size_hint_x: 1
                    size_hint_y: 0.15
                    spacing: 10

                    MDRectangleFlatIconButton:
                        id: godziny
                        icon: 'hours-24'
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        text: 'Godziny'
                        size_hint_x: 0.33
                        font_size: '18sp'
                        on_release:
                            root.btn_godziny()
                            root.logic.select_godziny()
                    
                    MDRectangleFlatIconButton:
                        id: obiekt
                        icon: 'home-lightning-bolt'
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        text: 'Obiekt'
                        size_hint_x: 0.33
                        font_size: '18sp'
                        on_release: 
                            root.btn_obiekt()
                            root.open_obiekt_menu()

                    MDRectangleFlatIconButton:
                        id: date
                        icon: 'calendar-range'
                        text: 'Data'
                        font_size: '18sp'
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}
                        size_hint_x: 0.33
                        on_release: 
                            root.btn_show_calendar()
                            root.show_date_picker()

                MDScrollView:
                    size_hint_x: 0.85
                    size_hint_y: 0.65
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    MDList: 
                        id: scroll
                
                MDGridLayout: 
                    cols: 3
                    size_hint_x: 1
                    size_hint_y: 0.2

                    Text:
                        text: 'Godzin: 148'
                        halign: 'left'
                        font_size: '24sp'
                        font_style: 'H6'
                        
                    Text:
                        text: 'Etat: 22 zl'
                        halign: 'center'
                        font_size: '24sp'
                        font_style: 'H6'

                    Text:
                        text: 'Płatność: 4321'
                        halign: 'right'
                        font_size: '24sp'
                        font_style: 'H6'

                MDRectangleFlatIconButton:
                    text: "Dodać"
                    font_size: '28sp'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    size_hint_x: 1
                    on_release:
                        root.btn_dodac()

<Calendar>:
    BoxLayout:
        padding: 20

        DatePicker:
            on_select: 
                root.screen_manager.remove_calendar_screen()
        
<DateButton>:
    id: date_btn
    elevation: .1
    radius: dp(10)
    ripple_behavior: True
    Label:
        text: date_btn.text
        color: date_btn.text_color

<Widgets>
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint:(None, None)
    height: 600
    width: 300
    size_hint_x: 1
    
    MDBoxLayout:
        size_hint_y: 1
        height: 300
        orientation: "vertical"
        pos_hint: {'center_x': .5, 'center_y': .5}

        MDBoxLayout:
            pos_hint: {'center_x': .5, 'center_y': .5}
            orientation: "horizontal"

            MDRectangleFlatIconButton:
                text: "8"
                size_hint_x: 1
                on_release:
                    root.add_8_godzin()
                    root.main_screen_logic.dialog.dismiss()

            MDRectangleFlatIconButton:
                text: "10"
                size_hint_x: 1
                on_release:
                    root.add_10_godzin()
                    root.main_screen_logic.dialog.dismiss()

            MDRectangleFlatIconButton:
                text: "12"
                size_hint_x: 1
                on_release:
                    root.add_12_godzin()
                    root.main_screen_logic.dialog.dismiss()
        
        MDLabel:

        MDBoxLayout:
            pos_hint: {'center_x': .5, 'center_y': .5}
            orientation: "vertical"

            MDSlider:
                value: root.progress
                hint: True
                min: 0
                max: 24

            MDLabel:
                pos_hint: {'center_x': .5, 'center_y': .5}

            MDRectangleFlatIconButton:
                pos_hint: {'center_x': .5, 'center_y': .5}
                text: "Ok"
                size_hint_x: 0.5
                on_release:
                    root.press_ok()
                    root.main_screen_logic.dialog.dismiss()
